config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]
  
  resources :videos, only: [:show, :new, :create]
  resources :markers, only: [:show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :user
  belongs_to :video
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :time, presence: true
  
  has_many :markers
  has_many :users, through: :markers
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :markers
  has_many :videos, through: :markers
end

app/models/video.rb
class Video < ApplicationRecord
  validates :video_id, presence: true, length: { maximum: 255 }
  validates :video_title, presence: true, length: { maximum: 255 }
  validates :channel_title, presence: true, length: { maximum: 255 }
  validates :thumbnail_url, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def read(item)
    id = item.id
    snippet = item.snippet    
    video_id = id.video_id
    video_title = snippet.title
    channel_title = snippet.channel_title 
    thumbnail_url= snippet.thumbnails.medium.url
    
    {
      video_id: video_id,
      video_title: video_title,
      channel_title: channel_title, 
      thumbnail_url: thumbnail_url,
    }
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def show
    @marker = Marker.find(params[:id])
  end
  
  def new
    @video = Video.find_by(id: params[:id])
    @marker = Marker.new
  end
   
  def create
    @video = Video.find_by(video_id: params[:video_id])
    @marker = Marker.new(video: @video,time: params[:time],content: params[:content])
    @marker.user_id = current_user.id
    if @marker.save
      flash[:success] = 'しおりを保存しました。'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'しおりを保存できませんでした。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @marker.destroy
    flash[:success] = 'しおりを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
 
  def correct_user
    @marker = current_user.markers.find_by(id: params[:id])
    unless @marker
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @markers = @user.markers
    @marker = Marker.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
   private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :require_user_logged_in
  require 'google/apis/youtube_v3'
 
 def show
   @marker = Marker.find(params[:id])
 end
 
  def new
    @videos = []
    
    @keyword = params[:q]
    if  @keyword.present?
      youtube = Google::Apis::YoutubeV3::YouTubeService.new
      youtube.key = "AIzaSyBygnUHbJ6EfyBuzIoVNBkAFv1QCzImt-4"
      results = youtube.list_searches(part="snippet" , 
                                    type: "video" ,
                                    q: @keyword , 
                                    max_results: 12 , 
                                    order: :date , 
      )
      
      results.items.each do |item|
        video = Video.find_or_initialize_by(read(item))
        @videos << video
      end
    end
  end
  
  def create
    @video = Video.find_or_initialize_by(video_id: params[:video_id])

    unless @video.persisted?
      # @video が保存されていない場合、先に @video を保存する
      youtube = Google::Apis::YoutubeV3::YouTubeService.new
      youtube.key = "AIzaSyBygnUHbJ6EfyBuzIoVNBkAFv1QCzImt-4"
      results = youtube.list_searches(part="snippet" ,
                                      type: "video" ,
                                      q: @video.video_id,
                                      max_results: 1 ,)

      results.items.each do |item|
        @video = Video.new(read(item))
        @video.save
      end
    end
    
    redirect_to new_marker_path(id: @video.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=identicon"
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2019 Videomarker.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/logo.png" alt="Videomarker"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to new_video_path do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                動画を探す
              <% end %>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="shortcut icon" href="images/favicon.ico">
  
    <title>Videomarker</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/markers/_marker_form.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <%= form_tag(markers_path) do %>
        　  <%= hidden_field_tag :video_id, video.video_id %>
        　  <p>Timeは "hh:mm:ss" の形式で入力してください。</p>
        　<div class="form-group">
            <label>Time</label>
            <%= text_field_tag :time %>
          </div>  
          
          <div class="form-group">
            <label>Memo</label>
            <%= text_area_tag :content %>
          </div>
          
          <%= submit_tag 'しおりを挟む', class: 'btn btn-primary btn-block' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/markers/_markers.html.erb
<% if markers %>
  <div class="row">
    <% markers.each do |marker| %>
        <div class="marker">
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-info">
              <div class="panel-heading text-center">
                <img src="<%= marker.video.thumbnail_url %>" alt="" >
              </div>
              <div class="panel-body">
                <p class="video-title"><%= link_to marker.video.video_title, video_path(marker.id) %></p>
                <p class="channel-title"><%= marker.video.channel_title %></p>
              </div>
              <div class="panel-footer">
                <p class="marker-memo"><%= marker.content %></p>
                <div style="text-align:center;">
                  <% if current_user == marker.user %>
                      <%= link_to "Delete", marker, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/markers/new.html.erb
<div class="player text-center">
  <p><%= @video.video_title %></p>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @video.video_id %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <p><%= @video.channel_title %></p>
</div>

<%= render 'markers/marker_form', video: @video %>

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
  </div>
  <div class="button">
    <% unless logged_in? %>
      <%= link_to '登録はこちら', signup_path, class: 'btn btn-info btn-lg' %>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
</div>
<%= render 'markers/markers', videos: @videos, markers: @markers %>

app/views/videos/_play_button.html.erb
<%= form_tag(videos_path) do %>
  <%= hidden_field_tag :video_id, video.video_id %>
  <%= hidden_field_tag :video_title, video.video_title %>
  <%= hidden_field_tag :channel_title, video.channel_title %>
  <%= hidden_field_tag :thumbnail_url, video.thumbnail_url %>
  <%= submit_tag 'Play', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/videos/_videos.html.erb
<% if videos %>
  <div class="row">
    <% videos.each do |video| %>
        <div class="video">
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-info">
              <div class="panel-heading text-center">
                <img src="<%= video.thumbnail_url %>" alt="" >
              </div>
              <div class="panel-body">
                <p class="video-title"><%= video.video_title %></p>
              </div>
              <div class="panel-footer text-center">
                <p class="channel-title"><%= video.channel_title %></p>
                <div class="buttons text-center">
                  <%= render 'play_button', video: video %>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/videos/new.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(new_video_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :q, @keyword, class: 'form-control input-lg', placeholder: "キーワードを入力", size: 40 %>
        </div>
        <%= submit_tag '動画を検索', class: 'btn btn-primary btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'videos', videos: @videos %>

app/views/videos/show.html.erb
<div class="player text-center">
    <p><%= @marker.video.video_title %></p>
    <% start = @marker.time.strftime("%-H:%-M:%-S") %>
    <div class="box">
        <span class="box-title"><%= start %></span>
        <p><%= @marker.content %></p>
    </div>
    <% seconds = start.split(/:/).map(&:to_i).inject{|x,y| x*60+y} %>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @marker.video.video_id %>?start=<%= seconds %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <p><%= @marker.video.channel_title %></p>
</div>